modelcheckpoint:
  _target_: Models.custom_checkpoint.ModelCheckpoint
  save_dir: '..\Image_Category_Classification\Pytorch_Lightning_Version\checkpoint_7'
  best_model_name: "best_model"

checkpoint_loss:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  dirpath: '..\Image_Category_Classification\Pytorch_Lightning_Version\checkpoint_7'
  filename: "best-loss-{epoch:02d}-{val_loss:.2f}"
  monitor: "val_loss"
  save_last: True
  save_top_k: 1
  mode: "min"

checkpoint_accuracy:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  dirpath: '..\Image_Category_Classification\Pytorch_Lightning_Version\checkpoint_7'
  filename: "best_accuracy-{epoch:02d}-{val_accuracy:.4f}"
  monitor: "val_accuracy"
  save_top_k: 1 
  mode: "max"

logging: 
  logs: '..\ML_Projects\Image_Category_Classification\Pytorch_Lightning_Version\logs_7'

load_from_checkpoint:
  best_model_path: '..\Image_Category_Classification\Pytorch_Lightning_Version\checkpoint_7\best-loss-epoch=04-val_loss=0.01.ckpt'   



 
  

  